@extends('layouts.front')

@section('title')
Term & Conditions
@endsection

@section('content')
   
    <section class="section-name  padding-y-sm">
      <div class="container">
      
      <header class="section-heading">
        <h3 class="section-title">Term & Conditions</h3>
      </header><!-- sect-heading -->
  
      <h4>General Terms</h4>
      <p class="text-justify">By accessing and placing an order with Diserv Official Store, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Diserv Official Store.
        Under no circumstances shall Diserv Official Store team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site. even if Diserv Official Store team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
        Diserv Official Store will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>

      <h4>License</h4>
      <p class="text-justify">Diserv Official Store grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and Diserv Official Store ("we," "our," or "us") grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.</p>

      <h4>Definitions and key terms</h4>
      <p class="text-justify">For this Terms & Conditions:</p>
      <ul>
        <li class="text-justify">Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
          provide analytics, remember information about you such as your language preference or login information.</li>
        <li class="text-justify">Company: when this policy mentions "Company," "we," "us," or "our," it refers to Diserv Official Store that is responsible for your
          information under this Privacy Policy.</li>
        <li class="text-justify">Country: where Diserv Official Store or the owners/founders of Diserv Official Store are based in this case is Indonesia.</li>
        <li class="text-justify">Customer: refers to the company, organization or person that signs up to use the Diserv Official Store Service to manage the
          relationships with your consumers or service users.</li>
        <li class="text-justify">Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Diserv
          Official Store and use the services.</li>
        <li class="text-justify">IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These
          numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a
          device is connecting to the Internet.</li>
        <li class="text-justify">Personnel: refers to those individuals who are employed by Diserv Official Store or are under contract to perform a service on
          behalf of one of the parties.</li>
        <li class="text-justify">Personal Data: any information that directly, indirectly, or in connection with other information - including a personal
          identification number – allows for the identification or identifiability of a natural person.</li>
        <li class="text-justify">ervice: refers to the service provided by Diserv Official Store as described in the relative terms (if available) and on this
          platform.</li>
        <li class="text-justify">Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our
          content or whose products or services we think may interest you. . Website: Diserv Official Store's site, which can be accessed via this URL: http://diserv.test/.</li>
        <li class="text-justify">You: a person or entity that is registered with Diserv Official Store to use the Services.</li>
      </ul>

      <h4>Restrictions</h4>
      <p class="text-justify"> You agree not to, and you will not permit others to:</p>
      <ul>
        <li class="text-justify">License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or
          make the platform available to any third party.</li>
        <li class="text-justify">Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.</li>
        <li class="text-justify">Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers or the licensors of the service.</li>
      </ul>

      <h4>Return and Refund Policy</h4>
      <p class="text-justify">Thanks for shopping with us. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products. As with any shopping experience, there are terms and conditions that apply to transactions at our company. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase from us, you agree to the terms along with our Privacy Policy. If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>

      <h4>Your Suggestions</h4>
      <p class="text-justify"> Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to us with respect to the service shall remain the sole and exclusive property of us. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.</p>

      <h4>Your Consent</h4>
      <p class="text-justify"> We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.</p>

      <h4>Links to Other Websites</h4>
      <p class="text-justify">Our service may contain links to other websites that are not operated by Us. If you click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms & Conditions of every site you visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services.</p>

      <h4>Cookies</h4>
      <p class="text-justify">We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our service but are nonessential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>

      <h4>Changes To Our Terms & Conditions</h4>
      <p class="text-justify">You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.</p>

      <h4>Modifications to Our service</h4>
      <p class="text-justify"> We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.</p>

      <h4>Updates to Our service</h4>
      <p class="text-justify">We may from time to time provide enhancements or improvements to the features/ functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement. </p>

      <h4>Third-Party Services</h4>
      <p class="text-justify">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</p>
      
      <h4>Miscellaneous</h4>
      <p class="text-justify">f for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of us. We will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. We operate and control our Service from our offices in Indonesia. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access our Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate our Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and us concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.</p>
     
      <h4>Disclaimer</h4>
      <p class="text-justify">We are not responsible for any content, code or any other imprecision. We do not provide warranties or guarantees. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
      <p class="text-justify">Our Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. We are a distributor and not a publisher of the content supplied by third parties, as such, our exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via our Service. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with our Service or on sites that may appear as links on our Service, or in the products provided as a part of, or otherwise in connection with, our Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, we do not warrant that our Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
     
      <h4>Contact Us</h4>
      <p class="text-justify">Don't hesitate to contact us if you have any questions.</p>
      <ul>
        <li>Via Email: cs.diserv@gmail.com</li>
        <li>Via Phone Number: +6281354307748</li>
        <li>Via this Address: Jl. Menara Air 1 No.26, Sekeloa, Kecamatan Coblong, Kota Bandung, Jawa Barat 40113</li>
      </ul>
      <!-- container // -->
      </section>
@endsection